// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC78mNUwe1Tj95mhDCA6jL0fmT46tpRkA',
    appId: '1:7944645716:web:8e38692ba099a6a24351c1',
    messagingSenderId: '7944645716',
    projectId: 'fluttergo',
    authDomain: 'fluttergo-ccb51.firebaseapp.com',
    storageBucket: 'fluttergo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMSV86oCuwLNmehltqoEcu_-kvyxFeH84',
    appId: '1:7944645716:android:0511feb91b8f43fe4351c1',
    messagingSenderId: '7944645716',
    projectId: 'fluttergo',
    storageBucket: 'fluttergo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzf8WpFml1DDIrONwGeZBbkTOfP3TJakI',
    appId: '1:7944645716:ios:e59813aa3fe801874351c1',
    messagingSenderId: '7944645716',
    projectId: 'fluttergo',
    storageBucket: 'fluttergo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzf8WpFml1DDIrONwGeZBbkTOfP3TJakI',
    appId: '1:7944645716:ios:e59813aa3fe801874351c1',
    messagingSenderId: '7944645716',
    projectId: 'fluttergo',
    storageBucket: 'fluttergo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC78mNUwe1Tj95mhDCA6jL0fmT46tpRkA',
    appId: '1:7944645716:web:18cf47ea3cff7ae04351c1',
    messagingSenderId: '7944645716',
    projectId: 'fluttergo',
    authDomain: 'fluttergo-ccb51.firebaseapp.com',
    storageBucket: 'fluttergo.appspot.com',
  );
}
